use std::path::Path;
use url::Url;

#[derive(Debug, Clone)]
pub struct Cookie {
    pub domain: String,
    pub path: String,
    pub secure: bool,
    pub expires: i64,
    pub name: String,
    pub value: String,
}

// ── CookieJar ────────────────────────────────────────────────────────────────

/// A simple cookie jar that holds cookies and provides URL-based matching.
#[derive(Debug, Clone, Default)]
pub struct CookieJar {
    cookies: Vec<Cookie>,
}

impl CookieJar {
    pub fn new() -> Self {
        Self {
            cookies: Vec::new(),
        }
    }

    pub fn from_cookies(cookies: Vec<Cookie>) -> Self {
        Self { cookies }
    }

    pub fn add(&mut self, cookie: Cookie) {
        self.cookies.push(cookie);
    }

    pub fn merge(&mut self, cookies: Vec<Cookie>) {
        self.cookies.extend(cookies);
    }

    pub fn cookies(&self) -> &[Cookie] {
        &self.cookies
    }

    /// Return all cookies whose domain and path match the given URL.
    pub fn get_cookies_for_url(&self, url: &Url) -> Vec<&Cookie> {
        let host = match url.host_str() {
            Some(h) => h,
            None => return Vec::new(),
        };
        let path = url.path();

        self.cookies
            .iter()
            .filter(|c| domain_matches(host, &c.domain) && path.starts_with(&c.path))
            .collect()
    }

    /// Format matching cookies as a `Cookie` header value: `name=value; name2=value2`.
    pub fn to_header_value(&self, url: &Url) -> Option<String> {
        let matched = self.get_cookies_for_url(url);
        if matched.is_empty() {
            return None;
        }
        Some(
            matched
                .iter()
                .map(|c| format!("{}={}", c.name, c.value))
                .collect::<Vec<_>>()
                .join("; "),
        )
    }
}

/// Check if a host matches a cookie domain.
/// A cookie domain `.example.com` matches `sub.example.com` and `example.com`.
fn domain_matches(host: &str, cookie_domain: &str) -> bool {
    let domain = cookie_domain.trim_start_matches('.');
    host == domain || host.ends_with(&format!(".{}", domain))
}

// ── Netscape cookie file I/O ─────────────────────────────────────────────────

/// Load cookies from a Netscape-format cookies.txt file.
pub fn load_cookies_file(path: &Path) -> anyhow::Result<Vec<Cookie>> {
    let content = std::fs::read_to_string(path)?;
    let mut cookies = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() >= 7 {
            cookies.push(Cookie {
                domain: parts[0].to_string(),
                path: parts[2].to_string(),
                secure: parts[3].eq_ignore_ascii_case("true"),
                expires: parts[4].parse().unwrap_or(0),
                name: parts[5].to_string(),
                value: parts[6].to_string(),
            });
        }
    }
    Ok(cookies)
}

/// Save cookies in Netscape cookie-file format.
pub fn save_cookies_file(cookies: &[Cookie], path: &Path) -> anyhow::Result<()> {
    use std::io::Write;
    let mut file = std::fs::File::create(path)?;
    writeln!(file, "# Netscape HTTP Cookie File")?;
    writeln!(
        file,
        "# This file was generated by yt-dlp-rs. Do not edit."
    )?;
    writeln!(file)?;
    for c in cookies {
        // Format: domain  include_subdomains  path  secure  expires  name  value
        let include_subdomains = if c.domain.starts_with('.') {
            "TRUE"
        } else {
            "FALSE"
        };
        let secure = if c.secure { "TRUE" } else { "FALSE" };
        writeln!(
            file,
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            c.domain, include_subdomains, c.path, secure, c.expires, c.name, c.value
        )?;
    }
    Ok(())
}

// ── Browser cookie extraction ────────────────────────────────────────────────

/// Extract cookies from a browser by name ("chrome" or "firefox").
pub fn extract_browser_cookies(browser: &str) -> anyhow::Result<Vec<Cookie>> {
    match browser.to_lowercase().as_str() {
        "chrome" | "chromium" => extract_chrome_cookies(),
        "firefox" => extract_firefox_cookies(),
        other => anyhow::bail!("Unsupported browser for cookie extraction: {}", other),
    }
}

/// Extract cookies from Google Chrome on macOS.
///
/// Chrome encrypts cookie values with Keychain on macOS. This function reads
/// the structure and returns what it can. Encrypted values will be empty.
fn extract_chrome_cookies() -> anyhow::Result<Vec<Cookie>> {
    let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("Cannot determine home directory"))?;
    let cookies_db = home
        .join("Library/Application Support/Google/Chrome/Default/Cookies");

    if !cookies_db.exists() {
        anyhow::bail!(
            "Chrome cookies database not found at: {}",
            cookies_db.display()
        );
    }

    // Shell out to sqlite3 to read the cookies database.
    // We copy the file first because Chrome may hold a lock on it.
    let tmp_dir = std::env::temp_dir();
    let tmp_db = tmp_dir.join("yt_dlp_rs_chrome_cookies.db");
    std::fs::copy(&cookies_db, &tmp_db)?;

    let output = std::process::Command::new("sqlite3")
        .arg("-separator")
        .arg("\t")
        .arg(&tmp_db)
        .arg("SELECT host_key, path, is_secure, expires_utc, name, value FROM cookies")
        .output()?;

    // Clean up temp file (best-effort)
    let _ = std::fs::remove_file(&tmp_db);

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("sqlite3 failed for Chrome cookies: {}", stderr);
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let cookies = parse_sqlite_cookie_output(&stdout);

    // TODO: Decrypt Chrome cookie values using macOS Keychain.
    // Chrome encrypts values with a key stored in the Keychain under
    // "Chrome Safe Storage". The encrypted_value column (blob) needs to be
    // decrypted with AES-128-CBC using a PBKDF2-derived key.
    // For now, cookies with empty `value` fields likely have encrypted values
    // stored in the `encrypted_value` column which we are not reading yet.

    if cookies.is_empty() {
        tracing::warn!("No cookies extracted from Chrome. Values may be encrypted.");
    }

    Ok(cookies)
}

/// Extract cookies from Firefox on macOS.
fn extract_firefox_cookies() -> anyhow::Result<Vec<Cookie>> {
    let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("Cannot determine home directory"))?;
    let profiles_dir = home.join("Library/Application Support/Firefox/Profiles");

    if !profiles_dir.exists() {
        anyhow::bail!(
            "Firefox profiles directory not found at: {}",
            profiles_dir.display()
        );
    }

    // Find the first profile directory that contains cookies.sqlite
    let mut cookies_db = None;
    if let Ok(entries) = std::fs::read_dir(&profiles_dir) {
        for entry in entries.flatten() {
            let candidate = entry.path().join("cookies.sqlite");
            if candidate.exists() {
                cookies_db = Some(candidate);
                break;
            }
        }
    }

    let cookies_db = cookies_db.ok_or_else(|| {
        anyhow::anyhow!("No cookies.sqlite found in any Firefox profile")
    })?;

    // Copy to temp to avoid lock issues
    let tmp_dir = std::env::temp_dir();
    let tmp_db = tmp_dir.join("yt_dlp_rs_firefox_cookies.db");
    std::fs::copy(&cookies_db, &tmp_db)?;

    let output = std::process::Command::new("sqlite3")
        .arg("-separator")
        .arg("\t")
        .arg(&tmp_db)
        .arg("SELECT host, path, isSecure, expiry, name, value FROM moz_cookies")
        .output()?;

    let _ = std::fs::remove_file(&tmp_db);

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("sqlite3 failed for Firefox cookies: {}", stderr);
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    Ok(parse_sqlite_cookie_output(&stdout))
}

/// Parse tab-separated sqlite3 output into Cookie structs.
/// Expected columns: domain, path, secure (0/1), expires, name, value
fn parse_sqlite_cookie_output(output: &str) -> Vec<Cookie> {
    let mut cookies = Vec::new();
    for line in output.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.splitn(6, '\t').collect();
        if parts.len() >= 6 {
            cookies.push(Cookie {
                domain: parts[0].to_string(),
                path: parts[1].to_string(),
                secure: parts[2] == "1" || parts[2].eq_ignore_ascii_case("true"),
                expires: parts[3].parse().unwrap_or(0),
                name: parts[4].to_string(),
                value: parts[5].to_string(),
            });
        }
    }
    cookies
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_domain_matches() {
        assert!(domain_matches("example.com", ".example.com"));
        assert!(domain_matches("sub.example.com", ".example.com"));
        assert!(domain_matches("example.com", "example.com"));
        assert!(!domain_matches("notexample.com", ".example.com"));
        assert!(!domain_matches("other.com", "example.com"));
    }

    #[test]
    fn test_cookie_jar_matching() {
        let mut jar = CookieJar::new();
        jar.add(Cookie {
            domain: ".example.com".into(),
            path: "/".into(),
            secure: false,
            expires: 0,
            name: "session".into(),
            value: "abc123".into(),
        });
        jar.add(Cookie {
            domain: ".other.com".into(),
            path: "/".into(),
            secure: false,
            expires: 0,
            name: "token".into(),
            value: "xyz".into(),
        });

        let url = Url::parse("https://www.example.com/page").unwrap();
        let matched = jar.get_cookies_for_url(&url);
        assert_eq!(matched.len(), 1);
        assert_eq!(matched[0].name, "session");

        let header = jar.to_header_value(&url).unwrap();
        assert_eq!(header, "session=abc123");
    }

    #[test]
    fn test_parse_sqlite_output() {
        let output = ".example.com\t/\t1\t1700000000\tsid\tabc123\n\
                       .other.com\t/path\t0\t0\ttoken\txyz789\n";
        let cookies = parse_sqlite_cookie_output(output);
        assert_eq!(cookies.len(), 2);
        assert_eq!(cookies[0].domain, ".example.com");
        assert!(cookies[0].secure);
        assert_eq!(cookies[1].name, "token");
        assert!(!cookies[1].secure);
    }
}
